/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-02-02 06:39:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.About;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>About Us | ARGOCAP</title>\r\n");
      out.write("<!---Custom Css File!--->\r\n");
      out.write("<link rel=\"icon\" href=\"/img/ARGO.png\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"about.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<nav>\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<a href=\"/index.html\"><img src=\"/img/ARGOCAP.png\"\r\n");
      out.write("				alt=\"Logo Image\">\r\n");
      out.write("		</div>\r\n");
      out.write("		</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"hamburger\">\r\n");
      out.write("			<div class=\"line1\"></div>\r\n");
      out.write("			<div class=\"line2\"></div>\r\n");
      out.write("			<div class=\"line3\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"google_translate_element\"></div>\r\n");
      out.write("		<ul class=\"nav-links\">\r\n");
      out.write("			<li><a href=\"/index.html\">Home</a></li>\r\n");
      out.write("			<li><a href=\"about/aboutus.html\">About Us</a></li>\r\n");
      out.write("			<li><a href=\"#\">Government Schemes</a></li>\r\n");
      out.write("			<li><a href=\"#\">Organic Farming</a></li>\r\n");
      out.write("			<li><a href=\"/contact/contactus.html\">Contact Us</a></li>\r\n");
      out.write("			<li><button class=\"login-button\" href=\"#\">Login</button></li>\r\n");
      out.write("			<li><button class=\"join-button\" href=\"#\">Join</button></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"about-us scroll-container\">\r\n");
      out.write("		<div class=\"about\">\r\n");
      out.write("			<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"GOV\" style=\"text-align: center;\">\r\n");
      out.write("					<p style=\"height: 0px;\"></p>\r\n");
      out.write("					<h1 style=\"text-align: center;\">\r\n");
      out.write("						<span style=\"font-size: xx-large;\">Government schemes</span>\r\n");
      out.write("					</h1>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<b>There are several government schemes implemented in many\r\n");
      out.write("								countries to support farmers and agricultural development. Here\r\n");
      out.write("								are some examples of government schemes for farmers:</b>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Subsidies and Grants:</b> Governments often provide subsidies\r\n");
      out.write("						and grants to farmers to promote agricultural activities. These\r\n");
      out.write("						can include subsidies on fertilizers, seeds, and irrigation\r\n");
      out.write("						equipment, as well as infrastructure development and farm\r\n");
      out.write("						modernization grants.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Crop Insurance:</b> Crop insurance schemes protect farmers from\r\n");
      out.write("						crop losses due to natural disasters, pests, or diseases. The\r\n");
      out.write("						government typically provides financial support or partners with\r\n");
      out.write("						insurance companies to offer affordable insurance coverage for\r\n");
      out.write("						farmers.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Farm Credit and Loans:</b> Governments may establish special\r\n");
      out.write("						lending institutions or programs to provide affordable credit and\r\n");
      out.write("						loans to farmers. These programs help farmers access funds for\r\n");
      out.write("						purchasing seeds, fertilizers, machinery, or for other\r\n");
      out.write("						agricultural needs.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Price Support and Minimum Support Price (MSP):</b> Governments\r\n");
      out.write("						may guarantee a minimum price for certain crops to protect farmers\r\n");
      out.write("						from market fluctuations and ensure their income stability. This\r\n");
      out.write("						minimum support price is often announced by the government at the\r\n");
      out.write("						beginning of the planting season.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Irrigation Schemes:</b> Governments may invest in irrigation\r\n");
      out.write("						infrastructure and schemes to ensure farmers have access to\r\n");
      out.write("						reliable water sources for irrigation. These schemes can include\r\n");
      out.write("						building canals, and reservoirs, or implementing drip irrigation\r\n");
      out.write("						systems.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b><br /></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Agricultural Extension Services:</b> Governments often\r\n");
      out.write("						establish agricultural extension services to provide technical\r\n");
      out.write("						guidance, training, and information to farmers. These services\r\n");
      out.write("						help farmers adopt modern farming techniques, improve\r\n");
      out.write("						productivity, and address various agricultural challenges.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<b>Research and Development Initiatives:</b> Governments invest in\r\n");
      out.write("						agricultural research and development to develop new varieties of\r\n");
      out.write("						crops, improve farming practices, and address challenges related\r\n");
      out.write("						to pests, diseases, and climate change. These initiatives aim to\r\n");
      out.write("						enhance agricultural productivity and sustainability.\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">\r\n");
      out.write("						<br />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"text-align: justify;\">It's important to note that\r\n");
      out.write("						specific schemes and their names may vary from country to country.\r\n");
      out.write("						The examples provided here are general categories, and the actual\r\n");
      out.write("						schemes available in a particular country will depend on its\r\n");
      out.write("						government's policies and priorities.</div>\r\n");
      out.write("					<p></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<div id=\"google_translate_element\"></div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function googleTranslateElementInit() {\r\n");
      out.write("			new google.translate.TranslateElement({\r\n");
      out.write("				pageLanguage : 'en'\r\n");
      out.write("			}, 'google_translate_element');\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"https://translate.google.com/translate_a/element.js?\r\n");
      out.write("cb=googleTranslateElementInit\">\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js\"\r\n");
      out.write("		integrity=\"sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==\"\r\n");
      out.write("		crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
